[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.evolution"

[deploy]
healthcheckPath = "/manager/fetchInstances"
healthcheckTimeout = 60
restartPolicyType = "on-failure"

[[services]]
name = "evolution-api"

[services.source]
repo = "leandromei/autocred-evolution-api"
branch = "main"

[[services.variables]]
EVOLUTION_API_KEY = "autocred-2024-super-secret-key"
JWT_SECRET = "autocred-jwt-ultra-secret-2024"
INSTANCE_TOKEN = "autocred-instance-token-2024"
WEBHOOK_URL = "https://autocred-evolution.up.railway.app/webhook/whatsapp"
NODE_ENV = "production"
PORT = "8080"

[services.domains]
# Railway vai gerar automaticamente

[env]
AUTHENTICATION_TYPE = "apikey"
AUTHENTICATION_API_KEY = "autocred-evolution-key-2024"
AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES = "true"
DATABASE_ENABLED = "true"
DATABASE_CONNECTION_URI = "file:./db/evolution.db"
SERVER_TYPE = "http"
SERVER_PORT = "8081"
CORS_ORIGIN = "*"
CORS_METHODS = "POST,GET,PUT,DELETE"
CORS_CREDENTIALS = "true"
WEBHOOK_GLOBAL_ENABLED = "true"
WEBHOOK_GLOBAL_URL = "https://autocredd-production.up.railway.app/webhook/whatsapp"
LOG_LEVEL = "info"
QRCODE_LIMIT = "30" 